### ISSUE TITLE
Extra #include "lvgl/lvgl.h" in lv_tutorial_responsive.c causes build issues

### ISSUE THREAD

**Issue by ChanFDavis** [littlevgl/lv_sim_eclipse_sdl#50]
The source file, _lv\_examples/lv\_tutorial/9\_responsive/lv\_tutorial\_responsive.c_, has `#include "lvgl/lvgl.h"`, while the associated header has the correct `#include "../../../lvgl/lvgl.h"`. 

Removing the include statement from the source file fixes the issue.

**Comment by kisvegabor** [comment]
I've fixed it [here](https://github.com/littlevgl/lv_examples/commit/1aa59a562983a82a2149fa5489c1cfba6e61759e). Actually `lvgl.h` doesn't needs to be included in the c file because it is included in `lv_tutorial_responsive.h` too.
