### ISSUE TITLE
lv_examples @ 85a6d71 (Release v6.1) not found

### ISSUE THREAD

**Issue by tjstyle** [littlevgl/lv_sim_eclipse_sdl#52]
Just try to clone lv_sim_eclipse_sdl Today, but got an error on cloning lv_example submodule.
checking lv_example, I can't see the v6.1 branch.

**Comment by kisvegabor** [comment]
Upps, I forgot to psóush commits to lv_examples.

It should work now.

**Comment by tjstyle** [comment]
Yup!, It's OK now. Thanks!
