### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by w8jcik** [littlevgl/lv_sim_eclipse_sdl#55]
@kisvegabor Could you create tags for different versions of lvgl? Right now the only tag present here is v5.2.

I have identified two commits for v5.3 and v6.0

v5.3: 72578733e0cdafe7415e27034ad5bc363fcc24f4
update to lvgl v5.3
kisvegabor committed on Feb 1, 2019

v6.0: e36087b8154ce78a62ceaa6696bf3e3ef735f008
Merge branch 'master' of https://github.com/littlevgl/pc_simulator
kisvegabor committed on Jun 30, 2019

**Comment by kisvegabor** [comment]
I'll create a script to run on releases. It'll update the `lv_port` and `lv_sim` projects and it can add tags too. I'll keep this in mind.

**Comment by w8jcik** [comment]
Great! Thank you a lot.
